version: 2
jobs:
  test:
    docker:
      # Available from https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.7.4

    steps:
      - checkout
      - run: make run
      - run: make flake
      - run: make lint
